// src/vue/NepaliDateTimePicker.vue
<template>
    <div>
      <datepicker v-model="selectedDate" :time-format="timeFormat" :date-format="dateFormat" :show-time="showTimeSelect" />
      <div v-if="selectedDate">
        <h3>Selected Date in Nepali Format:</h3>
        <p>{{ convertToNepaliDate(selectedDate) }}</p>
      </div>
    </div>
  </template>
  
  <script>
  import Datepicker from 'vuejs-datepicker';
  import { convertToNepaliDate } from '../core'; // Import core logic
  
  export default {
    components: {
      Datepicker
    },
    props: {
      value: {
        type: Date,
        required: false
      },
      showTimeSelect: {
        type: Boolean,
        default: true
      },
      timeFormat: {
        type: String,
        default: "HH:mm"
      },
      dateFormat: {
        type: String,
        default: "yyyy-MM-dd HH:mm"
      }
    },
    data() {
      return {
        selectedDate: this.value || null
      };
    },
    methods: {
      convertToNepaliDate
    }
  };
  </script>
  
  <style scoped>
  /* Add your CSS here */
  </style>

// src/react/NepaliDateTimePicker.jsx
import React, { useState } from 'react';
import DatePicker from 'react-datepicker';
import { convertToNepaliDate } from '../core'; // Import core logic
import 'react-datepicker/dist/react-datepicker.css';

const NepaliDateTimePicker = ({ onDateChange, value, showTimeSelect = true, timeFormat = "HH:mm", dateFormat = "yyyy-MM-dd HH:mm" }) => {
  const handleDateChange = (date) => {
    if (onDateChange) {
      onDateChange(date);
    }
  };

  return (
    <div>
      <DatePicker
        selected={value}
        onChange={handleDateChange}
        showTimeSelect={showTimeSelect}
        timeFormat={timeFormat}
        dateFormat={dateFormat}
        timeIntervals={15}
        timeCaption="Time"
        className="date-picker"
      />
      {value && (
        <div>
          <h3>Selected Date in Nepali Format:</h3>
          <p>{convertToNepaliDate(value)}</p>
        </div>
      )}
    </div>
  );
};

export default NepaliDateTimePicker;
